# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html

liip_imagine:
    resolvers:
        kbin.liip_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
                root_url: '%kbin_storage_url%'
                cache_prefix: cache
                visibility: public

    loaders:
        kbin.liip_loader:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem

    driver: gd
    cache: kbin.liip_resolver
    data_loader: kbin.liip_loader
    default_image: null
    twig:
        mode: lazy
    default_filter_set_settings:
        quality: 90

    controller:
        # Set this value to 301 if you want to enable image resolve redirects using 301 *cached* responses (eg. when behind Nginx)
        redirect_response_code: 302

    webp:
        generate: true
        quality: 90
        cache: ~
        data_loader: ~
        post_processors: []

    filter_sets:
        entry_thumb:
            filters:
                auto_rotate: ~
                thumbnail: { size: [380, 380], mode: inset }
        avatar_thumb:
            filters:
                auto_rotate: ~
                thumbnail: { size: [100, 100], mode: fixed }
        post_thumb:
            filters:
                auto_rotate: ~
                thumbnail: { size: [600, 500], mode: inset }
        user_cover:
            filters:
                auto_rotate: ~
                thumbnail: { size: [1500, 500], mode: fixed }
        magazine_banner:
            filters:
                auto_rotate: ~
                thumbnail: { size: [1500, 300], mode: fixed }
