
version: "3.9"

services:
  www:
    # Use Docker image from ghcr.io (you can also a tag eg: "v1.4.1" instead of "latest"):
    image: "ghcr.io/mbinorg/mbin:latest"
    # Or if you want to build your own image:
    #build:
    #  context: ../
    #  dockerfile: docker/Dockerfile
    #image: mbin
    container_name: mbin-www
    restart: unless-stopped
    ports:
      - "8008:80"
    networks:
      - mbin_external_network
      - mbin_internal_network
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2019/metrics || exit 1"]
    volumes:
      - ./storage/caddy_config:/config
      - ./storage/caddy_data:/data
      - ./storage/media:/var/www/mbin/public/media
    environment:
      - SERVER_NAME=:80 # the address that the web server binds
      - PHP_FASTCGI_HOST=php:9000 # caddy forward traffic to this host via fastcgi
      - MERCURE_PUBLISHER_JWT_KEY=$MERCURE_JWT_SECRET
      - MERCURE_SUBSCRIBER_JWT_KEY=$MERCURE_JWT_SECRET
    env_file:
      - .env
    depends_on:
      - php

  php:
    # Use Docker image from ghcr.io (you can also a tag eg: "v1.4.1" instead of "latest"):
    image: "ghcr.io/mbinorg/mbin:latest"
    # Or if you want to build your own image:
    #build:
    #  context: ../
    #  dockerfile: docker/Dockerfile
    #image: mbin
    container_name: mbin-php
    restart: unless-stopped
    networks:
      - mbin_internal_network
    command: php-fpm
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "REQUEST_METHOD=GET SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping cgi-fcgi -bind -connect localhost:9000 || exit 1",
        ]
    volumes:
      - ./storage/media:/var/www/mbin/public/media
      - ./storage/logs:/var/www/mbin/var/log
      - ../config:/var/www/mbin/config
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  messenger:
    # Use Docker image from ghcr.io (you can also a tag eg: "v1.4.1" instead of "latest"):
    image: "ghcr.io/mbinorg/mbin:latest"
    # Or if you want to build your own image:
    #build:
    #  context: ../
    #  dockerfile: docker/Dockerfile
    #image: mbin
    container_name: mbin-messenger
    restart: unless-stopped
    networks:
      - mbin_internal_network
    command: bin/console messenger:consume scheduler_default old async outbox deliver inbox resolve receive failed --time-limit=3600
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'messenger[:]consume' || exit 1"]
    volumes:
      - ./storage/media:/var/www/mbin/public/media
      - ./storage/logs:/var/www/mbin/var/log
      - ../config:/var/www/mbin/config
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 6
    depends_on:
      - redis
      - db
      - rabbitmq

  redis:
    image: redis:alpine
    container_name: mbin-redis
    restart: unless-stopped
    networks:
      - mbin_internal_network
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"incease
    volumes:
      - ./storage/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  db:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: mbin-db
    restart: unless-stopped
    expose:
      - "5432"
    networks:
      - mbin_internal_network
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mbin
      - POSTGRES_USER=mbin

  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    container_name: mbin-rabbitmq
    restart: unless-stopped
    expose:
      - "5672"
    ports:
      - "15672:15672"
    networks:
      - mbin_external_network
      - mbin_internal_network
    environment:
      - RABBITMQ_DEFAULT_USER=mbin
    volumes:
      - ./storage/rabbitmq:/var/lib/rabbitmq

  # Enable AMQP Proxy within Docker
  # Be sure to update your .env file with using the AMQP Proxy port (5673 instead of 5672):
  #     MESSENGER_TRANSPORT_DSN=amqp://mbin:${RABBITMQ_PASSWORD}@rabbitmq:5673/%2f/messages
  #amqproxy:
  #  image: cloudamqp/amqproxy
  #  expose:
  #    - "5673"
  #  networks:
  #    - mbin_internal_network
  #  command: amqp://rabbitmq:5672

  # Add your favorite reverse proxy (e.g nginx) which accept incoming HTTPS
  # traffic and forward to http://www:80
  #nginx:
  #  image: nginx
  #  container_name: mbin-nginx
  #  ports:
  #    - 443:443
  #  networks:
  #    - mbin_external_network
  #    - mbin_internal_network
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf

  # Example of a SMTP docker service
  # More info: https://hub.docker.com/r/ixdotai/smtp
  #mailserver:
  #  image: ixdotai/smtp:latest
  #  networks:
  #    - mbin_external_network
  #    - mbin_internal_network
  #  environment:
  #    - SMARTHOST_ADDRESS=mail.mysmtp.com
  #    - SMARTHOST_PORT=587
  #    - SMARTHOST_USER=myuser
  #    - SMARTHOST_PASSWORD=secret
  #    - SMARTHOST_ALIASES=*.mysmtp.com

networks:
  mbin_external_network:
  mbin_internal_network:
    internal: true
