version: "3.9"

services:
  www:
    # Builds the Docker image from scratch
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: mbin
    # Or remove the build, context, dockerfile and image lines above and
    # use the pre-build image from ghcr.io (you can also a tag eg.: v1.0.0 instead of: latest):
    #image: "ghcr.io/mbinorg/mbin:latest"
    container_name: mbin-www
    restart: unless-stopped
    networks:
      - mbin_external_network
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2019/metrics || exit 1"]
    ports:
      - 8008:80
    volumes:
      - ./storage/caddy_config:/config
      - ./storage/caddy_data:/data
      - ./storage/media:/var/www/mbin/public/media
    environment:
      - SERVER_NAME=:80 # the address that the web server binds
      - PHP_FASTCGI_HOST=php:9000 # caddy forward traffic to this host via fastcgi
      - MERCURE_PUBLISHER_JWT_KEY=$MERCURE_JWT_SECRET
      - MERCURE_SUBSCRIBER_JWT_KEY=$MERCURE_JWT_SECRET
    depends_on:
      - php

  php:
    # Builds the Docker image from scratch
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: mbin
    # Or remove the build, context, dockerfile and image lines above and
    # use the pre-build image from ghcr.io (you can also a tag eg.: v1.0.0 instead of: latest):
    #image: "ghcr.io/mbinorg/mbin:latest"
    container_name: mbin-php
    restart: unless-stopped
    networks:
      - mbin_external_network
    command: php-fpm
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "REQUEST_METHOD=GET SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping cgi-fcgi -bind -connect localhost:9000 || exit 1",
        ]
    volumes:
      - ./storage/media:/var/www/mbin/public/media
      - ./storage/logs:/var/www/mbin/var/log
    # If you want to change configs locally, without rebuilding the image use:
    #  - ../config:/var/www/mbin/config
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  messenger:
    # Builds the Docker image from scratch
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: mbin
    # Or remove the build, context, dockerfile and image lines above and
    # use the pre-build image from ghcr.io (you can also a tag eg.: v1.0.0 instead of: latest):
    #image: "ghcr.io/mbinorg/mbin:latest"
    container_name: mbin-messenger
    restart: unless-stopped
    networks:
      - mbin_external_network
    command: bin/console messenger:consume scheduler_default async async_ap failed --time-limit=3600
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'messenger[:]consume' || exit 1"]
    volumes:
      - ./storage/media:/var/www/mbin/public/media
      - ./storage/logs:/var/www/mbin/var/log
    # If you want to change configs locally, without rebuilding the image use:
    #  - ../config:/var/www/mbin/config
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  redis:
    image: redis:alpine
    container_name: mbin-redis
    restart: unless-stopped
    networks:
      - mbin_external_network
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    volumes:
      - ./storage/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  db:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    container_name: mbin-db
    restart: unless-stopped
    networks:
      - mbin_external_network
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kbin
      - POSTGRES_USER=kbin

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mbin-rabbitmq
    restart: unless-stopped
    networks:
      - mbin_external_network
    environment:
      - RABBITMQ_DEFAULT_USER=kbin
    volumes:
      - ./storage/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672

  # Add your favorite reverse proxy (e.g nginx) which accept incoming HTTPS
  # traffic and forward to http://www:80
  #nginx:
  #  image: nginx
  #  container_name: mbin-nginx
  #  networks:
  #    - mbin_external_network
  #  ports:
  #    - 443:443
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf

  # Example of a SMTP docker service
  # More info: https://hub.docker.com/r/ixdotai/smtp
  #mailserver:
  #  image: ixdotai/smtp:latest
  #  networks:
  #    - mbin_external_network
  #  environment:
  #    - SMARTHOST_ADDRESS=mail.mysmtp.com
  #    - SMARTHOST_PORT=587
  #    - SMARTHOST_USER=myuser
  #    - SMARTHOST_PASSWORD=secret
  #    - SMARTHOST_ALIASES=*.mysmtp.com

networks:
  mbin_external_network:
