front:
  controller: App\Controller\Entry\EntryFrontController::front
  defaults: &front_defaults { subscription: home, content: default, sortBy: default, time: '∞', federation: all }
  path: /{subscription}/{content}/{sortBy}/{time}/{federation}
  methods: [GET]
  requirements: &front_requirement
    subscription: "%default_subscription_options%"
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"
    federation: "%default_federation_options%"
    content: "%default_content_options%"

front_sub:
  controller: App\Controller\Entry\EntryFrontController::front
  defaults: *front_defaults
  path: /{subscription}/{sortBy}/{time}/{federation}
  methods: [GET]
  requirements: *front_requirement

front_content:
  controller: App\Controller\Entry\EntryFrontController::front
  defaults: *front_defaults
  path: /{content}/{sortBy}/{time}/{federation}
  methods: [GET]
  requirements: *front_requirement

front_short:
  controller: App\Controller\Entry\EntryFrontController::front
  defaults: *front_defaults
  path: /{sortBy}/{time}/{federation}
  methods: [GET]
  requirements: *front_requirement

front_magazine:
  controller: App\Controller\Entry\EntryFrontController::magazine
  defaults: &front_magazine_defaults { content: all, sortBy: default, time: '∞', federation: all }
  path: /m/{name}/{content}/{sortBy}/{time}/{federation}
  methods: [GET]
  requirements: *front_requirement

front_magazine_short:
  controller: App\Controller\Entry\EntryFrontController::magazine
  defaults: &front_magazine_defaults
  path: /m/{name}/{sortBy}/{time}/{federation}
  methods: [GET]
  requirements: *front_requirement

# Microblog compatibility stuff, redirects from the old routes' URLs

posts_front:
  controller: App\Controller\Entry\EntryFrontController::frontRedirect
  defaults: { sortBy: default, time: '∞', federation: all, content: microblog }
  path: /microblog/{sortBy}/{time}
  methods: [ GET ]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"

posts_subscribed:
  controller: App\Controller\Entry\EntryFrontController::frontRedirect
  defaults: { sortBy: default, time: '∞', federation: all, content: microblog, subscription: 'sub' }
  path: /sub/microblog/{sortBy}/{time}
  methods: [ GET ]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"

posts_moderated:
  controller: App\Controller\Entry\EntryFrontController::frontRedirect
  defaults: { sortBy: default, time: '∞', federation: all, content: microblog, subscription: 'mod' }
  path: /mod/microblog/{sortBy}/{time}
  methods: [ GET ]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"

posts_favourite:
  controller: App\Controller\Entry\EntryFrontController::frontRedirect
  defaults: { sortBy: default, time: '∞', federation: all, content: microblog, subscription: 'fav' }
  path: /fav/microblog/{sortBy}/{time}
  methods: [ GET ]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"

magazine_posts:
  controller: App\Controller\Entry\EntryFrontController::magazineRedirect
  defaults: { sortBy: default, time: '∞', federation: all, content: microblog }
  path: /m/{name}/microblog/{sortBy}/{time}/{federation}
  methods: [ GET ]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"
    federation: "%default_federation_options%"
