api_notification_settings_update:
    controller: App\Controller\Api\Notification\NotificationSettingApi::update
    path: /api/notification/update/{targetType}/{targetId}/{setting}
    requirements:
        targetType: entry|post|magazine|user
        setting: Default|Loud|Muted
    methods: [ GET ]
    format: json
