api_bookmark_front:
    controller: App\Controller\Api\Bookmark\BookmarkListApiController::front
    path: /api/lists/show
    methods: [GET]
    format: json

api_bookmark_lists:
    controller: App\Controller\Api\Bookmark\BookmarkListApiController::list
    path: /api/lists
    methods: [GET]
    format: json

api_bookmark_lists_make_default:
    controller: App\Controller\Api\Bookmark\BookmarkListApiController::makeDefault
    path: /api/lists/{list_name}/makeDefault
    methods: [GET]
    format: json

api_bookmark_lists_edit_list:
    controller: App\Controller\Api\Bookmark\BookmarkListApiController::editList
    path: /api/lists/{list_name}
    methods: [POST]
    format: json

api_bookmark_lists_delete_list:
    controller: App\Controller\Api\Bookmark\BookmarkListApiController::deleteList
    path: /api/lists/{list_name}
    methods: [DELETE]
    format: json

api_subject_bookmark_standard:
    controller: App\Controller\Api\Bookmark\BookmarkApiController::subjectBookmarkStandard
    path: /api/bos/{subject_id}/{subject_type}
    requirements:
        subject_type: "%default_subject_type_options%"
    methods: [ GET ]
    format: json

api_subject_bookmark_to_list:
    controller: App\Controller\Api\Bookmark\BookmarkApiController::subjectBookmarkToList
    path: /api/bol/{subject_id}/{subject_type}/{list_name}
    requirements:
        subject_type: "%default_subject_type_options%"
    methods: [ GET ]
    format: json

api_subject_remove_bookmarks:
    controller: App\Controller\Api\Bookmark\BookmarkApiController::subjectRemoveBookmarks
    path: /api/rbo/{subject_id}/{subject_type}
    requirements:
        subject_type: "%default_subject_type_options%"
    methods: [ GET ]
    format: json

api_subject_remove_bookmark_from_list:
    controller: App\Controller\Api\Bookmark\BookmarkApiController::subjectRemoveBookmarkFromList
    path: /api/rbol/{subject_id}/{subject_type}/{list_name}
    requirements:
        subject_type: "%default_subject_type_options%"
    methods: [ GET ]
    format: json
