api_instance_details_retrieve:
  controller: App\Controller\Api\Instance\InstanceDetailsApi
  path: /api/instance
  methods: [ GET ]
  format: json

api_instance_modlog_retrieve:
  controller: App\Controller\Api\Instance\InstanceModLogApi::collection
  path: /api/modlog
  methods: [ GET ]
  format: json

api_instance_retrieve_votes:
  controller: App\Controller\Api\Instance\InstanceRetrieveStatsApi::votes
  path: /api/stats/votes
  methods: [ GET ]
  format: json

api_instance_retrieve_content:
  controller: App\Controller\Api\Instance\InstanceRetrieveStatsApi::content
  path: /api/stats/content
  methods: [ GET ]
  format: json

api_instance_retrieve_defederated_instances:
  controller: App\Controller\Api\Instance\InstanceRetrieveFederationApi::getDeFederated
  path: /api/defederated
  methods: [ GET ]
  format: json

api_instance_retrieve_federated_instances:
    controller: App\Controller\Api\Instance\InstanceRetrieveFederationApi::getFederated
    path: /api/federated
    methods: [ GET ]
    format: json

api_instance_retrieve_dead_instances:
    controller: App\Controller\Api\Instance\InstanceRetrieveFederationApi::getDead
    path: /api/dead
    methods: [ GET ]
    format: json

api_instance_retrieve_info:
  controller: App\Controller\Api\Instance\InstanceRetrieveInfoApi
  path: /api/info
  methods: [ GET ]
  format: json
